---
- name: Setup Lider in raft step 1-4
  hosts: '{{ myhosts }}'
  become: true
  # vars:
  #   oned_conf : /var/lib/docker/volumes/hvol/_data/etc/one/oned.conf

  tasks:
    - name: Change Listener adress on Leader
      ansible.builtin.lineinfile:
        path: '{{ oned_conf }}'
        regexp: '^LISTEN_ADDRESS = '
        line: LISTEN_ADDRESS = "0.0.0.0"

    # - name: Delete line
    #   community.general.ini_file:
    #     path: '{{ oned_conf }}'
    #     section: RAFT_LEADER_HOOK
    #     option: COMMAND
    #     state: absent
        # exclusive: 

    - name: Comments block
      ansible.builtin.replace:
        path: '{{ oned_conf }}'
        after: "# Executed when a server transits from follower->leader"
        before: "# Executed when a server transits from leader->follower"
        # before: "^DEFAULT_COST*$"
        regexp: '^(.+)$'
        replace: '# \1'

    # - name: Comments block
    #   ansible.builtin.replace:
    #     path: '{{ oned_conf }}'
    #     after: "# Executed when a server transits from leader->follower"
    #     before: '^$'
    #     regexp: '^(.+)$'
    #     replace: '# \1'
