---
- name: Set all IPv4 to file hosts
  hosts: '{{ myhosts }}'
  become: true

  tasks:
    - name: "host to all host from group single"
      ansible.builtin.blockinfile:
        block: |
          {% for item in groups['horizon'] %}
          {{ hostvars[item]['ansible_host'] }}    {{hostvars[item]['hostname'] }}
          {% endfor %}
        path: /etc/hosts
        state: present
