---
- name: Setup Part2 step 1-2
  hosts: '{{ myhosts }}'
  become: true
  vars:
    db_file_01: dump_from_lider_to_{{ second_id_server }}.sql

  tasks:
    - name: make backup DB
      community.docker.docker_container_exec:
        container: '{{ container_name }}'
        command: 'onedb backup -f -u oneadmin -p horizon -d opennebula {{ db_file_01 }}'

    - name: copy backup to host
      ansible.builtin.shell: "docker cp {{ container_name }}:/{{ db_file_01 }} /root/{{ db_file_01 }}"

    - name: copy db_file from {{ myhosts }} to {{ second_server_ip }} using Method Pull
      synchronize:
        mode: pull
        src: "/root/{{ db_file_01 }}"
        dest: "/root/{{ db_file_01 }}"
      delegate_to: '{{ second_server_ip }}'
      # register: syncfile

