---
- name: Setup RAFT Part1 step 5 -- restart HCS
  hosts: '{{ myhosts }}'
  become: true
  # vars:
  #   container_name: hcs

  tasks:
    - name: "Stopped {{ container_name }} on host {{ myhosts }}"
      community.docker.docker_container:
        name: '{{ container_name }}'
        state: stopped

    - name: "Started {{ container_name }} on host {{ myhosts }}"
      community.docker.docker_container:
        name: '{{ container_name }}'
        state: started
