---
- name: Playbook for copy to server container and run it
  hosts: '{{ myhosts }}'
  become: true

  tasks:
    - name: Run docker container
      community.docker.docker_container:
        name: hcs
        image: "hcs:{{ image_tag }}"
        state: started
        timeout: 90
        network_mode: host
        restart_policy: always
        security_opts: seccomp:unconfined
        volumes:
          - "/var/tmp:/var/tmp"
          - "hvol:/hvol"
