---
- name: Change file
  hosts: '{{ myhosts }}'
  become: true


  tasks:
  - name: Change output_format to json in lvm.conf
    ansible.builtin.replace:
      path: /etc/lvm/lvm.conf
      regexp: (^[^#].*)(basic(?!output_format))
      replace: '\1json'
