---
- name: Fetch HCS container to directory files
  hosts: '{{ myhosts }}'
  become: true
  # vars:
  #   web_build_path: "http://10.1.100.110/hcs/git"

  tasks:
    - name: 'Fetch from {{ web_build_path }} {{ hcs_container }} to directory files'
      ansible.builtin.get_url:
        url: "{{ web_build_path }}/{{ hcs_container }}"
        dest: /var/tmp/
        # flat: true

