---
- name: Delete files in folder
  hosts: '{{ myhosts }}'
  become: true
  # vars:
  #   directory: /data/0/docker/volumes/hvol/_data

  tasks:
    - name: Get directory listing
      ansible.builtin.shell: rbd ls '{{ ceph_pool }}'
        # path: "{{ directory }}"
        # file_type: any
        # hidden: yes
      register: directory_content_result

    # - name: print
    #   ansible.builtin.debug:
    #     var: directory_content_result


    - name: Remove directory content
      ansible.builtin.shell: rbd rm "{{ ceph_pool }}"/"{{ item }}"
      # file:
        # path: "{{ item.path }}"
        # state: absent
      # with_items: "{{ directory_content_result.files }}"
      with_items: "{{ directory_content_result.stdout_lines }}"
      # loop_control:
        # label: "{{ item.path }}"
        # label: "{{ item }}"
