---
- name: Delete files in folder
  hosts: '{{ myhosts }}'
  become: true
  vars:
    directory: /data/0/docker/volumes/hvol/_data

  tasks:
    - name: Get directory listing
      find:
        path: "{{ directory }}"
        file_type: any
        hidden: yes
      register: directory_content_result

    - name: Remove directory content
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ directory_content_result.files }}"
      loop_control:
        label: "{{ item.path }}"
