---
- name: Setup Lider in raft
  hosts: '{{ myhosts }}'
  become: true
  # vars:
  #   oned_conf : /var/lib/docker/volumes/hvol/_data/etc/one/oned.conf

  tasks:
    - name: Comments block
      ansible.builtin.replace:
        path: '{{ oned_conf }}'
        after: "# Executed when a server transits from follower->leader"
        before: '(^.\.s.*$)'
        regexp: '^(.+)$'
        replace: '# \1'

        # before: "# Executed when a server transits from leader->follower"
