---
- name: Setup RAFT FLOATING Step 1-6
  # hosts: '{{ myhosts }}'
  # hosts: h-115
  hosts: h-75
  become: true
  vars:
    main_br: 'hvssw0'
    raft_net_port: 'hcs0'

  tasks:
    - name: Step 1-2.. Add port {{ raft_net_port }} to Open vSwitch {{ main_br }} and set type internal
      openvswitch.openvswitch.openvswitch_port:
        bridge: '{{ main_br }}'
        port: '{{ port_raft }}'
        state: present
        set: interface {{ raft_net_port }} type=internal

    - name: Step 3.. Create symbol link net.hcs0 to net.lo
      ansible.builtin.file:
        path: /etc/init.d/net.{{ raft_net_port }}
        # path: /etc/init.d/net.hcs0
        src: /etc/init.d/net.lo
        state: link

    - name: Step 4.. Add {{ raft_net_port }} to /etc/conf.d/net file
      ansible.builtin.blockinfile:
        path: /etc/conf.d/net
        marker: "## {mark} Floating RAFT interface"
        block: "{{ lookup('ansible.builtin.template', 'templates/conf.d-net.hcs0.j2') }}"

    - name: Step 5-6.. Enable deamon for network interface {{ raft_net_port }}
      ansible.builtin.service:
        name: net.{{ raft_net_port }}
        state: started
        runlevel: default

