---
- name: Setup Lider in raft
  hosts: '{{ myhosts }}'
  become: true
  # vars:
  #   oned_conf : /var/lib/docker/volumes/hvol/_data/etc/one/oned.conf

  tasks:
    - name: Change Listener adress on Leader
      ansible.builtin.lineinfile:
        path: '{{ oned_conf }}'
        regexp: '^LISTEN_ADDRESS = '
        line: LISTEN_ADDRESS = "0.0.0.0"

    - name: Comments block
      ansible.builtin.replace:
        path: '{{ oned_conf }}'
        after: "RAFT_FOLLOWER_HOOK(.+)$"
        before: "^DEFAULT(.+)$"
        regexp: '^(.+)$'
        replace: '# \1'

    # - name: Comments block
    #   ansible.builtin.replace:
    #     path: '{{ oned_conf }}'
    #     after: "# Executed when a server transits from leader->follower"
    #     before: '^$'
    #     regexp: '^(.+)$'
    #     replace: '# \1'
