---
- name: Set all IPv4 to file hosts
  hosts: h-1:h-2
  become: true

  tasks:
    - name: "host to all host from group single"
      ansible.builtin.blockinfile:
        block: |
          {% for host in groups['horizon'] %}
           '123'
          {{ ansible_default_ipv4.address }} {{ ansible_hostname }}
          {% endfor %}
        path: /root/1.txt
      # state: present
          # {% for host in groups['single'] %}
          # {{ ansible_default_ipv4.address }} {{ ansible_hostname }}
          # {{ hostvars[host]['ansible_facts']['ansible_hostname'] }}
