---
- name: Change file use template
  # hosts: '{{ myhosts }}'
  hosts: h-75
  become: true
  vars:
    # oned_conf : /var/lib/docker/volumes/hvol/_data/etc/one/oned.conf
    oned_conf : /root/oned.conf

  tasks:
    - name: Insert data to RAFT_LEADER_HOOK
      ansible.builtin.blockinfile:
        path: '{{ oned_conf }}'
        insertafter: "# Executed when a server transits from follower->leader"
        marker: "## {mark} modify change RAFT to LEADER"
        block: "{{ lookup('template', 'templates/oned-conf.leader.j2') }}"
