---
- name: Setup Lider in raft step 9
  # hosts: '{{ myhosts }}'
  hosts: h-75
  become: true
  vars:
    # oned_conf : /var/lib/docker/volumes/hvol/_data/etc/one/oned.conf
    oned_conf : /root/oned.conf
    onz_id_server: 0

  tasks:
    - name: Change Server_ID to {{ onz_id_server }} on Leader
      ansible.builtin.lineinfile:
        path: '{{ oned_conf }}'
        regexp: (^\s*SERVER_ID\s*=\s*)
        # line: "    SERVER_ID     = 0,"
        # line: \g<1>0,
        line: \g<1>{{ onz_id_server}},
        backrefs: yes
