---
- name: Setup Lider in raft step 1-4
  # hosts: '{{ myhosts }}'
  hosts: h-75
  become: true
  vars:
    # oned_conf : /var/lib/docker/volumes/hvol/_data/etc/one/oned.conf
    oned_conf : /root/oned.conf
    # begin: `#`

  tasks:
    - name: Remove parameters RAFT_LEADER_HOOK
      ansible.builtin.replace:
        path: '{{ oned_conf }}'
        after: "# Executed when a server transits from follower->leader"
        regexp: ^RAFT_LEADER_HOOK(.*\n){4}
        replace: ''

    - name: Remove parameters RAFT_FOLLOWER_HOOK
      ansible.builtin.replace:
        path: '{{ oned_conf }}'
        after: "# Executed when a server transits from leader->follower"
        regexp: ^RAFT_FOLLOWER_HOOK(.*\n){4}
        replace: ''


    # - name: Insert data to RAFT_LEADER_HOOK
    #   ansible.builtin.blockinfile:
    #     path: '{{ oned_conf }}'
    #     insertafter: "# Executed when a server transits from follower->leader"
    #     marker: "## {mark} modify change RAFT to LEADER"

        # marker_begin:  
        # block: |
        #   123
        #   345
        # marker_begin: "# Executed when a server transits from follower->leader"
        # marker_end: '^\s*$'
        # block: |
        #   RAFT_LEADER_HOOK = [
        #   COMMAND = "raft/vip.sh",
        #   ARGUMENTS = "leader hcs0 10.0.10.13/24 10.10.10.9"
        #   ]
