---
- name: Change logrotate in container
  hosts: '{{ myhosts }}'
  become: true

  tasks:
    # - name: Change global config
    #   ansible.builtin.lineinfile:
    #     path: /etc/mysql/my.cnf
    #     line: binlog_expire_logs_seconds = 172800  # for 2 days 2*24*60*60 = 172800

    - name: Restart hcs
      community.docker.docker_container:
        name: hcs
        state: started
        restart: true
