---
- name: Remove comments or remove hook in /etc/one/oned.conf
  hosts: '{{ myhosts }}'
  become: true

  tasks:
    - name: remove blocks
      ansible.builtin.blockinfile:
        path: '{{ oned_conf }}'
        insertafter: "# Executed when a server transits from follower->leader"
        block: |
          RAFT_LEADER_HOOK = [
              COMMAND = "raft/vip.sh",
              ARGUMENTS = "leader hcs0 10.0.10.13/24 10.10.10.1"
          ]
          
          # Executed when a server transits from leader->follower
          RAFT_FOLLOWER_HOOK = [
              COMMAND = "raft/vip.sh",
              ARGUMENTS = "follower hcs0 10.0.10.13/24 10.10.10.1"
          ]
        state: absent
        marker: ""
